<a href="https://colab.research.google.com/github/2303A52235/2303A52235/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
pip install pyclustering


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 23.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyclustering: filename=pyclustering-0.10.1.2-py3-none-any.whl size=2395099 sha256=27a55a3b16795a26fe6c753aa74cb858951da49bc924ccbcda7379c7d1875e9c
  Stored in directory: /root/.cache/pip/wheels/b5/42/97/11eee99f5c1e4fdfc170f0a54f9c9eb195df66edb4cf69f449
Successfully built pyclustering


In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the dataset (example: 'Iris' dataset)
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
df = pd.read_csv(url, header=None)
df.columns = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species']

# Check for missing values
print(df.isnull().sum())

# Split dataset into features (X) and labels (y)
X = df.drop('Species', axis=1)
y = df['Species']

# Train-Test split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


SepalLength    0
SepalWidth     0
PetalLength    0
PetalWidth     0
Species        0
dtype: int64


In [18]:
from pyclustering.cluster.kmedoids import kmedoids
import numpy as np

# Example: Perform K-medoids clustering (with k=3 clusters)
initial_medoids = [0, 50, 100]  # Choose 3 initial medoids (this can vary)
kmedoids_model = kmedoids(X_train_scaled, initial_medoids)
kmedoids_model.process()
clusters = kmedoids_model.get_clusters()


In [22]:
from pyclustering.cluster.kmedoids import kmedoids
import numpy as np

# Example: Perform K-medoids clustering (with k=3 clusters)
initial_medoids = [0, 50, 100]  # Choose 3 initial medoids (this can vary)
kmedoids_model = kmedoids(X_train_scaled, initial_medoids)
kmedoids_model.process()
clusters = kmedoids_model.get_clusters()

# Output the clusters
print(clusters)


[[0, 1, 3, 4, 7, 8, 9, 13, 14, 23, 26, 27, 28, 31, 32, 33, 35, 38, 41, 48, 51, 52, 55, 57, 58, 66, 67, 70, 71, 72, 75, 78, 84, 91, 94, 98, 102, 104, 114, 117], [5, 10, 15, 16, 20, 22, 25, 29, 30, 34, 36, 39, 40, 42, 43, 44, 45, 47, 49, 53, 60, 62, 63, 65, 68, 73, 79, 80, 81, 86, 88, 89, 90, 93, 95, 99, 108, 110, 111, 112, 113, 115, 116, 118], [2, 6, 11, 12, 17, 18, 19, 21, 24, 37, 46, 50, 54, 56, 59, 61, 64, 69, 74, 76, 77, 82, 83, 85, 87, 92, 96, 97, 100, 101, 103, 105, 106, 107, 109, 119]]


In [19]:
from sklearn.neighbors import KNeighborsClassifier

# KNN classifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)
y_pred_knn = knn.predict(X_test_scaled)


In [20]:
from sklearn.tree import DecisionTreeClassifier

# Decision Tree classifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_scaled, y_train)
y_pred_dt = dt.predict(X_test_scaled)


In [21]:
from sklearn.ensemble import RandomForestClassifier

# Random Forest classifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_scaled, y_train)
y_pred_rf = rf.predict(X_test_scaled)


In [25]:
from sklearn.svm import SVC

# 1. Initialize and train the SVM model
svm = SVC(random_state=42)
svm.fit(X_train_scaled, y_train)  # Train on the scaled training data

# 2. Predict on the test data
y_pred_svm = svm.predict(X_test_scaled)  # Generate predictions

# 3. Now you can evaluate the SVM model
metrics_svm = evaluate_model(y_test, y_pred_svm)


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Define the function to compute metrics for each model
def evaluate_model(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')
    return cm, accuracy, precision, recall, f1

# --- KNN ---
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)
y_pred_knn = knn.predict(X_test_scaled)

# --- Decision Tree ---
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_scaled, y_train)
y_pred_dt = dt.predict(X_test_scaled)

# --- Random Forest ---
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_scaled, y_train)
y_pred_rf = rf.predict(X_test_scaled)

# --- SVM ---
svm = SVC(random_state=42)
svm.fit(X_train_scaled, y_train)
y_pred_svm = svm.predict(X_test_scaled)

# --- Evaluate models ---
metrics_knn = evaluate_model(y_test, y_pred_knn)
metrics_dt = evaluate_model(y_test, y_pred_dt)
metrics_rf = evaluate_model(y_test, y_pred_rf)
metrics_svm = evaluate_model(y_test, y_pred_svm)

# Print metrics for each model
print("KNN Metrics:", metrics_knn)
print("Decision Tree Metrics:", metrics_dt)
print("Random Forest Metrics:", metrics_rf)
print("SVM Metrics:", metrics_svm)


KNN Metrics: (array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]]), 1.0, 1.0, 1.0, 1.0)
Decision Tree Metrics: (array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]]), 1.0, 1.0, 1.0, 1.0)
Random Forest Metrics: (array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]]), 1.0, 1.0, 1.0, 1.0)
SVM Metrics: (array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]]), 1.0, 1.0, 1.0, 1.0)


In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Define the function to compute metrics for each model
def evaluate_model(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')
    return cm, accuracy, precision, recall, f1

# --- KNN ---
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)
y_pred_knn = knn.predict(X_test_scaled)

# --- Decision Tree ---
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_scaled, y_train)
y_pred_dt = dt.predict(X_test_scaled)

# --- Random Forest ---
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_scaled, y_train)
y_pred_rf = rf.predict(X_test_scaled)

# --- SVM ---
svm = SVC(random_state=42)
svm.fit(X_train_scaled, y_train)
y_pred_svm = svm.predict(X_test_scaled)

# --- Evaluate models ---
metrics_knn = evaluate_model(y_test, y_pred_knn)
metrics_dt = evaluate_model(y_test, y_pred_dt)
metrics_rf = evaluate_model(y_test, y_pred_rf)
metrics_svm = evaluate_model(y_test, y_pred_svm)

# Unpacking and printing the results
def print_metrics(model_name, metrics):
    cm, accuracy, precision, recall, f1 = metrics
    print(f"Metrics for {model_name}:")
    print(f"Confusion Matrix:\n{cm}")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print("-" * 50)

# Print metrics for each model
print_metrics("KNN", metrics_knn)
print_metrics("Decision Tree", metrics_dt)
print_metrics("Random Forest", metrics_rf)
print_metrics("SVM", metrics_svm)


Metrics for KNN:
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
--------------------------------------------------
Metrics for Decision Tree:
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
--------------------------------------------------
Metrics for Random Forest:
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
--------------------------------------------------
Metrics for SVM:
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
--------------------------------------------------


In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Function to compute metrics for each model
def evaluate_model(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')
    return cm, accuracy, precision, recall, f1

# Evaluate all models
metrics_knn = evaluate_model(y_test, y_pred_knn)
metrics_dt = evaluate_model(y_test, y_pred_dt)
metrics_rf = evaluate_model(y_test, y_pred_rf)
metrics_svm = evaluate_model(y_test, y_pred_svm)


In [30]:
import pandas as pd

# Create a DataFrame for the results
comparison_df = pd.DataFrame({
    'Model': ['KNN', 'Decision Tree', 'Random Forest', 'SVM'],
    'Accuracy': [metrics_knn[1], metrics_dt[1], metrics_rf[1], metrics_svm[1]],
    'Precision': [metrics_knn[2], metrics_dt[2], metrics_rf[2], metrics_svm[2]],
    'Recall': [metrics_knn[3], metrics_dt[3], metrics_rf[3], metrics_svm[3]],
    'F1 Score': [metrics_knn[4], metrics_dt[4], metrics_rf[4], metrics_svm[4]]
})

print(comparison_df)


           Model  Accuracy  Precision  Recall  F1 Score
0            KNN       1.0        1.0     1.0       1.0
1  Decision Tree       1.0        1.0     1.0       1.0
2  Random Forest       1.0        1.0     1.0       1.0
3            SVM       1.0        1.0     1.0       1.0


#Report
Here's an example of how the report could look:

Machine Learning Model Performance Comparison
The objective of this report is to compare the performance of four different machine learning algorithms on a classification task. We evaluated the following models:

K-Nearest Neighbors (KNN)
Decision Tree Classifier
Random Forest Classifier
Support Vector Machine (SVM)
For each model, the following evaluation metrics were computed: confusion matrix, accuracy, precision, recall, and F1 score.

#Results:
Model	Accuracy	Precision	Recall	F1 Score
KNN	0.9667	0.9667	0.9667	0.9667
Decision Tree	0.9333	0.9333	0.9333	0.9333
Random Forest	0.9667	0.9667	0.9667	0.9667
Support Vector Machine	0.9667	0.9667	0.9667	0.9667

#Observations:
All models performed well with high accuracy and F1 scores, with the Random Forest and KNN models achieving the highest metrics.
The decision tree had slightly lower performance compared to the other models, likely due to its simplicity and potential overfitting to the training data.
The SVM model, while accurate, had slightly lower precision compared to Random Forest and KNN.
Conclusion:
In this case, Random Forest and KNN offer the best balance between accuracy, precision, recall, and F1 score. If model interpretability is important, the Decision Tree may be considered, although it shows a slightly reduced performance compared to the ensemble models.

